# =============================================
# CONFIGURACI\u00d3N DE MONGODB
# =============================================
spring.data.mongodb.uri=mongodb+srv://oscardejesus0461_db_user:Perrolobo0@jesusproyect.mx6bdzn.mongodb.net/liga_futbol?appName=JesusProyect

spring.data.mongodb.database=liga_futbol

# =============================================
# CONFIGURACI\u00d3N DEL SERVIDOR
# =============================================
server.port=${PORT:8080}

logging.level.org.springframework.data.mongodb=DEBUG

spring.application.name=liga-futbol
